version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: game-db
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - game-db:/var/lib/mysql
      - ./config/mysql/conf.d:/etc/mysql/conf.d
      - ./config/mysql/db:/docker-entrypoint-initdb.d/
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
volumes:
  game-db:
    external:
      name: game-db

